name: shared_lib
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com
# author: ericwindmill

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  built_value: "^6.1.6"
  built_collection: "^4.0.0"

dev_dependencies:
  build_runner: "^1.1.1"
  built_value_generator: "^6.1.6"
  test: ^1.0.0

executables:
  weather:
